server:
  port: 8888


spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native # 파일시스템에 저장
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/Documents/config-native # 파일시스템 위치
        git:
#          uri: file:///${user.home}/Documents/config
          uri: https://github.com/ash-tiger95/spring-cloud-config # Local GIT에 저장

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh